"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
export default function ForgotPasswordPage() {
  const [message,setMessage]=useState<string|null>(null),[devUrl,setDevUrl]=useState<string|null>(null),[loading,setLoading]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);const form=new FormData(event.currentTarget);const response=await fetch("/api/auth/forgot-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:form.get("email")})});const data=await response.json() as {message?:string;error?:string;devUrl?:string};setLoading(false);setMessage(data.message??data.error??"Request failed");setDevUrl(data.devUrl??null);}
  return <AuthCard title="Forgot password" description="Enter your account email. The reset link is valid for 30 minutes."><form onSubmit={submit} className="space-y-4"><input required name="email" type="email" autoComplete="email" placeholder="name@company.com" className="admin-input w-full"/><button disabled={loading} className="w-full rounded-full bg-foreground px-4 py-3 font-bold text-background disabled:opacity-50">{loading?"Sending…":"Send reset link"}</button></form>{message?<p className="mt-4 text-sm">{message}</p>:null}{devUrl?<Link href={devUrl} className="mt-3 block break-all text-sm underline">Open local development reset link</Link>:null}<Link href="/login" className="mt-6 block text-center text-sm underline">Back to sign in</Link></AuthCard>;
}
function AuthCard({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <main className="container mx-auto flex min-h-[calc(100vh-4rem)] max-w-lg items-center px-7 py-12"><section className="card-lg w-full p-8"><p className="kicker">Account security</p><h1 className="mt-3 font-serif text-4xl">{title}</h1><p className="text-soft mb-7 mt-2 text-sm">{description}</p>{children}</section></main>}
