import { Document, Packer, Paragraph, TextRun } from "docx";
import { NextResponse } from "next/server";
import { findUserById, getDownloadableReport, recordReportAccess, writeAuditLog } from "@/lib/auth/db";
import { clientIp } from "@/lib/auth/request-security";
import { verifyDownloadToken } from "@/lib/reports/download-token";
import { increment } from "@/lib/observability/metrics";
import { log } from "@/lib/observability/logger";

export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params,token=new URL(request.url).searchParams.get("token");const verified=token?verifyDownloadToken(token):null;if(!verified||verified.reportId!==id)return NextResponse.json({error:"Invalid or expired download link"},{status:403});const user=await findUserById(verified.userId);if(!user)return NextResponse.json({error:"Account unavailable"},{status:403});const report=await getDownloadableReport(user,id);if(!report)return NextResponse.json({error:"Download permission revoked"},{status:403});const markdown=report.result.feature?.reportMarkdown??`# ${report.result.region.name}\n\nRisk score: ${report.result.riskScore}/100`;const document=new Document({sections:[{children:markdown.split(/\n+/).filter(Boolean).map(line=>new Paragraph({children:[new TextRun({text:line.replace(/^#+\s*/,"") ,bold:line.startsWith("#")})]}))}]});const buffer=await Packer.toBuffer(document);await Promise.all([recordReportAccess({reportId:id,userId:user.id,action:"download",ipAddress:clientIp(request),userAgent:request.headers.get("user-agent")??undefined}),writeAuditLog(user.id,"report.download","report",id)]);increment("cuvee_report_downloads_total","Authorized report downloads");log("info","report.download",{userId:user.id,reportId:id,organizationId:user.organizationId});return new Response(new Uint8Array(buffer),{headers:{"content-type":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","content-disposition":`attachment; filename="cuvee-report-${id.slice(0,8)}.docx"`,"cache-control":"private, no-store"}});}
